version: '3.4'

services:
  
  coronavirusservice:
    image: coronavirusservice
    build:
        context: .  
        dockerfile: coronavirusservice/Dockerfile
    depends_on: 
        - seq
        - postgresql_database

  postgresql_database:
    image: postgres:latest
    environment: 
        - POSTGRES_USER=admin
        - POSTGRES_PASSWORD=adminadmin
        - POSTGRES_DB=Metrics
    ports:
        - "5432:5432"
    restart: unless-stopped
    volumes: 
        - databasedata:/var/lib/postgresql/data/

  pgadmin:
    image: dpage/pgadmin4
    environment: 
        - PGADMIN_DEFAULT_EMAIL=pgadmin4@pgadmin.org
        - PGADMIN_DEFAULT_PASSWORD=admin
    ports: 
        - "5050:80"
    restart: unless-stopped
    volumes: 
        - ./pgadmin:/root/.pgadmin
  
  seq:
    image: datalust/seq:latest
    ports: 
        - "5341:80"
    environment: 
        ACCEPT_EULA: Y
    restart: unless-stopped
    volumes: 
        - ./seq-data:/data

volumes: 
  databasedata: