FROM mcr.microsoft.com/dotnet/core/runtime:3.1 AS base
WORKDIR /app

FROM mcr.microsoft.com/dotnet/core/sdk:3.1 AS build
WORKDIR /src
COPY ["coronavirusservice/coronavirusservice.csproj", "coronavirusservice/"]
RUN dotnet restore "coronavirusservice/coronavirusservice.csproj"
COPY . .
WORKDIR "/src/coronavirusservice"
RUN dotnet build "coronavirusservice.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "coronavirusservice.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "coronavirusservice.dll"]
